### ISSUE TITLE
Query about parameter ranges

### ISSUE THREAD

**Issue by joezuntz** [miknab/EuclidEmulator#2]
Hi there.

In the ee_input.py files the input parameters are checked against ranges.  These are slightly different from the ranges in the C code, which match the ones in the paper, presumably to give a little boundary at the edge.

The h_range listed there looks wrong, though - I think it may be mistakenly set to the same as the n_s range.

Cheers,
Joe Zuntz

**Comment by miknab** [comment]
Hi Joe,

Thanks for this comment. You were absolutely right, the upper limit of the h range was of course wrong. It was also a bit ugly that the ranges in the CLI and the wrapper were not consistent. This I have changed now. The ranges are now consistently defined as follows in both the CLI and e2py:

`[lower_new, upper_new] = [mu - 5*sigma, mu + 5*sigma]`

where 

`mu = (lower_old + upper_old) / 2`

and

`sigma = (upper_old - lower_old)/12`

and `upper_old` and `lower_old` are the parameter box limits defined in Knabenhans et al. 2019, equation (7).

Please let me know if you are happy with this solution (also if you are not, of course).

Cheers,
Mischa

**Comment by joezuntz** [comment]
Thanks so much!  I'm actually planning to use the C code directly in my code, since it fits in quite well with what I'm doing already, rather than going through the python layer.  But I just wanted to check what the limits are supposed to be, mainly.  That seems to be reasonable, though is there a reason you don't want to use the full range?

On a separate question - would you be happy with me distributing the EuclidEmulator, perhaps with some minor modifications, with a module making it accessible through the parameter estimation code CosmoSIS (https://bitbucket.org/joezuntz/cosmosis)?  Also I could contribute any changes back if they were more widely useful?

Many thanks,
Joe

**Comment by miknab** [comment]
Hi Joe,

The reason for the trust region is purely heuristical. Mathematically there is no justification for that inner region. But when we plotted error maps we detected the largest errors near the edges of the parameter box. Fig. 3 of our paper shows the basic behaviour (although it's not constructed from the "real" emulator): Looking at the right panel, you see the largest errors near the bottom edge. That's why we decided to stay within the inner region.

About your plan to integrate EuclidEmulator into CosmoSIS: Sure, you're very welcome to do so. EuclidEmulator is published under GPL3, so you can use it freely. I would of course appreciate a citation :-D.

Cheers,
Mischa

PS: I will now close this issue. Do not hesitate to contact me via email directly (mischak@physik.uzh.ch) if you like to discuss more.
